JacobMoller/BDSAProject

.github/workflows/main.yml

One build and test Action. 
Ran it after we fixed main. 

WorkFlowAction

---

ProjectBank/Core/IProjectRepository.cs
ProjectBank/Infrastructure/ProjectRepository.cs

FixmainBuild

---

.gitignore
ProjectBank/Client/Pages/MyProjects.razor
ProjectBank/Core/IProjectRepository.cs
ProjectBank/Core/IUserRepository.cs
ProjectBank/Core/ProjectDTO.cs
ProjectBank/Core/Role.cs
ProjectBank/Core/UserDTO.cs
ProjectBank/Infrastructure.Tests/ContextSetup.cs
ProjectBank/Infrastructure.Tests/GlobalUsings.cs
ProjectBank/Infrastructure.Tests/ProjectRepositoryTests.cs
ProjectBank/Infrastructure.Tests/UserRepositoryTests.cs
ProjectBank/Infrastructure/ProjectBankContext.cs
ProjectBank/Infrastructure/ProjectRepository.cs
ProjectBank/Infrastructure/User.cs
ProjectBank/Infrastructure/UserRepository.cs
ProjectBank/Server/Model/SeedExtensions.cs
ProjectBank/Server/Program.cs

This is the first iteration of out repositories. We are gonna look this through and apply changes and review it later on aswell.
Also resolves:
#223 
#184
#211

Implement repos

---

ProjectBank/Core/IProjectRepository.cs
ProjectBank/Infrastructure.Tests/ProjectRepositoryTests.cs
ProjectBank/Infrastructure/ProjectRepository.cs
ProjectBank/Server/Controllers/MyProjectsController.cs

added method for reading users projects

---

ProjectBank/Client/Pages/EditProject.razor
ProjectBank/Client/Pages/ProjectPage.razor
ProjectBank/Core/IProjectRepository.cs
ProjectBank/Core/ProjectDTO.cs
ProjectBank/Infrastructure.Tests/ProjectRepositoryTests.cs
ProjectBank/Infrastructure/Migrations/20211210110719_RenameUserId.Designer.cs
ProjectBank/Infrastructure/Migrations/20211210110719_RenameUserId.cs
ProjectBank/Infrastructure/Project.cs
ProjectBank/Infrastructure/ProjectRepository.cs
ProjectBank/Server/Controllers/MyProjectsController.cs
ProjectBank/Server/Controllers/ProjectsController.cs
ProjectBank/Server/Model/SeedExtensions.cs

Method for reading users on project

---

ProjectBank/Infrastructure.Tests/ProjectRepositoryTests.cs

fix assert null

---

ProjectBank/Client/Shared/FormComponent.razor

Changed regex in FormComponent to only capture relevant information for tags.

Tags now appear correctly in browser as well as database

---

ProjectBank/Client/Pages/Index.razor
ProjectBank/Client/Shared/LoginDisplay.razor

User needs to log in to see projects.

Need to login before seeing projects.

---

ProjectBank/Client/Pages/ProjectPage.razor
ProjectBank/Core/UserDTO.cs
ProjectBank/Infrastructure.Tests/UserRepositoryTests.cs
ProjectBank/Infrastructure/UserRepository.cs

Username shown on project page + UserDetailsDTO takes string role 

---

ProjectBank/Infrastructure.Tests/UserRepositoryTests.cs
ProjectBank/Infrastructure/ProjectRepository.cs

test coverage

---

ProjectBank/Core/IProjectRepository.cs
ProjectBank/Core/Response.cs
ProjectBank/Infrastructure.Tests/ProjectRepositoryTests.cs
ProjectBank/Infrastructure/ProjectRepository.cs
ProjectBank/Server/Model/SeedExtensions.cs

Added responses on methods in project repository. Resolves #260

added responses

---

ProjectBank/Client/Pages/ProjectPage.razor

Adds back button on ProjectPage

---

ProjectBank/Client/Shared/LoginDisplay.razor

_White text and white logout button_

Login/Logout Button Styling

---

ProjectBank/Client/Shared/LoginDisplay.razor

Doesnt redirect to /login

---

ProjectBank/Client/Pages/ProjectPage.razor

Changed "Go back"-button from \<a\> to \<button\>

Testapply2

---

ProjectBank/Client/Pages/Index.razor

Description cut at 150 chars

---

ProjectBank/Client/Pages/Authentication.razor

Redirects to the index page when logging out. 

Redirects to login when logged out.

---

ProjectBank/Client/Pages/MyProjects.razor

added delete alert

---

ProjectBank/Client/Pages/Index.razor
ProjectBank/Infrastructure/ProjectRepository.cs
ProjectBank/Server/Controllers/ApplyController.cs

Add section "Your projects" on ExploreProjectsPage for student to see the projects that they have applied for.

Your projects

---

ProjectBank/Client/Pages/Index.razor
ProjectBank/Client/Pages/ProjectPage.razor
ProjectBank/Infrastructure/ProjectRepository.cs
ProjectBank/Server/Controllers/ApplyController.cs

* Apply Button now changes to grey and says "Applied" when student applies
* If a project is full the Apply button changes to grey and says "Project Full" (unless the user is one of the participants in which case it says "Applied")

Apply disabled on project full

---

ProjectBank/Client/Pages/CreateProject.razor
ProjectBank/Client/Pages/MyProjects.razor
ProjectBank/Client/Shared/FormComponent.razor
ProjectBank/Client/Shared/NavMenu.razor
ProjectBank/Server/Controllers/MyProjectsController.cs
ProjectBank/Server/Controllers/ProjectsController.cs

Alerts when creating, updating and deleting now fixed. 

alerts on create/update fixed

---

ProjectBank/Client/Pages/ProjectPage.razor

Apply success alert

---

ProjectBank/Client/Pages/MyProjects.razor

Time changed to Seconds

---

ProjectBank/Client/Shared/FormComponent.razor

Description for writing tags!
this is very small so i thought it okay not to do any tests.

Description

---

ProjectBank/Client/Pages/Index.razor
ProjectBank/Client/Pages/MyProjects.razor
ProjectBank/Client/Pages/ProjectPage.razor
ProjectBank/Infrastructure.Tests/ProjectRepositoryTests.cs
ProjectBank/Infrastructure/ProjectRepository.cs

removed comments

---

ProjectBank/Client/CustomAccountFactory.cs
ProjectBank/Client/Pages/CreateProject.razor
ProjectBank/Client/Pages/EditProject.razor
ProjectBank/Client/Pages/Index.razor
ProjectBank/Client/Pages/MyProjects.razor
ProjectBank/Client/Pages/ProjectPage.razor
ProjectBank/Client/Shared/FormComponent.razor
ProjectBank/Client/Shared/NavMenu.razor
ProjectBank/Infrastructure.Tests/ProjectRepositoryTests.cs
ProjectBank/Infrastructure/ProjectRepository.cs
ProjectBank/Infrastructure/UserRepository.cs
ProjectBank/Server.Integration.Tests/ProjectTests.cs

Do yourself a favor and hide whitespace 

Nullreferences

---

ProjectBank/Server/Model/SeedExtensions.cs

Added 5 participants to the project with id 3 ("Super Closed Project") which makes its status Status.Closed.

Add students to close a project

---

ProjectBank/Infrastructure/ProjectRepository.cs
ProjectBank/Server/Model/SeedExtensions.cs

The API for yourProjects now returns an empty list of ProjectDTO if the student has not applied 

Fix yourProjects container
